WebToi_final_01/Areas/Admin/Controllers/DanhMucAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebToi_final_01.Models;

namespace WebToi_final_01.Areas.Admin.Controllers
{
    public class DanhMucAdminController : Controller
    {
        private Shop con = new Shop();
        // GET: Admin/DanhMucAdmin
        [CustomAuthorize(Roles = "Admin")]

        public ActionResult Index()
        {

            var model = con.DanhMucs.ToList();
            return View(model);

        }
        //[CustomAuthorize(Roles = "Admin")]

        //public ActionResult ShowSp()
        //{

        //    var model = con.SanPhams.ToList();
        //    return View(model);

        //}

        // GET: Admin/DanhMucAdmin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/DanhMucAdmin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/DanhMucAdmin/Create
        [HttpPost]
        [CustomAuthorize(Roles = "Admin")]

        public ActionResult Create(DanhMuc model)
        {
            try
            {
                // TODO: Add insert logic here
                con.DanhMucs.Add(model);
                con.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/DanhMucAdmin/Edit/5
        [CustomAuthorize(Roles = "Admin")]

        public ActionResult Edit(int id)
        {

            var model = con.DanhMucs.Find(id);

            return View(model);

        }

        // POST: Admin/DanhMucAdmin/Edit/5
        [HttpPost]
        [CustomAuthorize(Roles = "Admin")]

        public ActionResult Edit(DanhMuc model)
        {
            try
            {
                var obj = con.DanhMucs.Find(model.MaDM);
                obj.TenDM = model.TenDM;

                con.SaveChanges();
                return RedirectToAction("Index");

            }
            catch
            {
                return Redirect("/Admin/DanhMucAd/Edit/" + model.MaDM);
            }
        }

        // GET: Admin/DanhMucAdmin/Delete/5
        [CustomAuthorize(Roles = "Admin")]

        public ActionResult Delete(int id)
        {

            var model = con.DanhMucs.Find(id);

            return View("Edit", model);

        }

        // POST: Admin/DanhMucAdmin/Delete/5
        [HttpPost]
        [CustomAuthorize(Roles = "Admin")]

        public ActionResult Delete(DanhMuc model)
        {
            try
            {
                // TODO: Add delete logic here
                var obj = con.DanhMucs.Find(model.MaDM);
                con.DanhMucs.Remove(obj);

                con.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebToi_final_01/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>


<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edmin</title>
    <link type="text/css" href="~/Content/Admin/css/bootstrap.min.css" rel="stylesheet">
    <link type="text/css" href="~/Content/Admin/css/bootstrap-responsive.min.css" rel="stylesheet">
    <link type="text/css" href="~/Content/Admin/css/theme.css" rel="stylesheet">
    <link type="text/css" href="~/Content/Admin/images/icons/css/font-awesome.css" rel="stylesheet">

    <script src="~/Content/Admin/js/jquery-1.9.1.min.js"></script>
    <script src="~/Content/Admin/js/jquery-ui-1.10.1.custom.min.js"></script>
    <script src="~/Content/Admin/js/bootstrap.min.js"></script>
    <script src="~/Content/Admin/js/datatables/jquery.dataTables.js"></script>
</head>
<body>

    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-inverse-collapse">
                    <i class="icon-reorder shaded"></i>
                </a>

                <a class="brand" href="index.html">
                    Admin
                </a>

                <div class="nav-collapse collapse navbar-inverse-collapse">
                    <ul class="nav nav-icons">
                        <li class="active">
                            <a href="#">
                                <i class="icon-envelope"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="icon-eye-open"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="icon-bar-chart"></i>
                            </a>
                        </li>
                    </ul>

                    <form class="navbar-search pull-left input-append" action="#">
                        <input type="text" class="span3">
                        <button class="btn" type="button">
                            <i class="icon-search"></i>
                        </button>
                    </form>

                    <ul class="nav pull-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Chọn các chức năng <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Item No. 1</a></li>

                                <li><a href="#">Don't Click</a></li>
                                <li class="divider"></li>
                                <li class="nav-header">Example Header</li>
                                <li><a href="#">A Separated link</a></li>
                            </ul>
                        </li>

                        <li>
                            <a href="#">
                                Thông tin người dùng
                            </a>
                        </li>
                        <li class="nav-user dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="/Content/Admin/images/user.png" class="nav-avatar" />
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Your Profile</a></li>
                                <li><a href="#">Edit Profile</a></li>
                                <li><a href="#">Account Settings</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                </div><!-- /.nav-collapse -->
            </div>
        </div><!-- /navbar-inner -->
    </div><!-- /navbar -->



    <div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="span3">
                    <div class="sidebar">

                        <ul class="widget widget-menu unstyled">
                            <li class="active">
                                <a href="/Admin/DanhMucAdmin">
                                    <i class="menu-icon icon-dashboard"></i>
                                    Sản phẩm
                                </a>
                            </li>
                            <li>
                                <a class="collapsed" data-toggle="collapse" href="#togglePages">
                                    <i class="menu-icon icon-bullhorn"></i>
                                    <i class="icon-chevron-down pull-right"></i><i class="icon-chevron-up pull-right"></i>
                                    Danh mục
                                </a>

                                <ul id="togglePages" class="collapse unstyled">
                                    <li>
                                        <a href="@Url.Action( "Index" ,"DanhMucAdmin" )">
                                            <i class="icon-inbox"></i>
                                            Danh sách
                                        </a>
                                    </li>
                                    <li>
                                        <a href="@Url.Action("Create", "DanhMucAdmin")">
                                            <i class="icon-inbox"></i>
                                            Tạo danh mục
                                        </a>
                                    </li>

                                </ul>
                            </li>

                            <li>
                                <a href="task.html">
                                    <i class="menu-icon icon-tasks"></i>
                                    Đơn hàng
                                    <b class="label orange pull-right">19</b>
                                </a>
                            </li>
                        </ul><!--/.widget-nav-->



                        <ul class="widget widget-menu unstyled">
                            <li>
                                <a class="collapsed" data-toggle="collapse" href="#togglePagesUser">
                                    <i class="menu-icon icon-cog"></i>
                                    <i class="icon-chevron-down pull-right"></i><i class="icon-chevron-up pull-right"></i>
                                    Người dùng
                                </a>

                                <ul id="togglePagesUser" class="collapse unstyled">
                                    <li>
                                        <a href="other-login.html">
                                            <i class="icon-inbox"></i>
                                            Login
                                        </a>
                                    </li>
                                    <li>
                                        <a href="other-user-profile.html">
                                            <i class="icon-inbox"></i>
                                            Profile
                                        </a>
                                    </li>
                                    <li>
                                        <a href="other-user-listing.html">
                                            <i class="icon-inbox"></i>
                                            All Users
                                        </a>
                                    </li>
                                </ul>
                            </li>

                            <li>
                                <a href="#">
                                    <i class="menu-icon icon-signout"></i>
                                    Logout
                                </a>
                            </li>
                        </ul>

                    </div><!--/.sidebar-->
                </div><!--/.span3-->

                <div class="span9">
                    @RenderBody();

                </div><!--/.span9-->
            </div>
        </div><!--/.container-->
    </div><!--/.wrapper-->

    <div class="footer">
        <div class="container">


            <b class="copyright">&copy; 2014 Edmin - EGrappler.com </b> All rights reserved.
        </div>
    </div>


    <script>
        $(document).ready(function () {
            $('.datatable-1').dataTable();
            $('.dataTables_paginate').addClass("btn-group datatable-pagination");
            $('.dataTables_paginate > a').wrapInner('<span />');
            $('.dataTables_paginate > a:first-child').append('<i class="icon-chevron-left shaded"></i>');
            $('.dataTables_paginate > a:last-child').append('<i class="icon-chevron-right shaded"></i>');
        });
    </script>
</body>